"""empty message

Revision ID: 9ecb36b38675
Revises: e455451361ab
Create Date: 2017-07-19 01:21:07.964568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ecb36b38675'
down_revision = 'e455451361ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('issues_ibfk_1', 'issues', type_='foreignkey')
    op.drop_column('issues', 'subissue_id')
    op.add_column('subissues', sa.Column('issue_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subissues', 'issues', ['issue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subissues', type_='foreignkey')
    op.drop_column('subissues', 'issue_id')
    op.add_column('issues', sa.Column('subissue_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('issues_ibfk_1', 'issues', 'subissues', ['subissue_id'], ['id'])
    # ### end Alembic commands ###
