"""empty message

Revision ID: b659b1190982
Revises: f38ddbbbd934
Create Date: 2017-08-08 21:00:54.799266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b659b1190982'
down_revision = 'f38ddbbbd934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('zip_code', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queries', 'zip_code')
    # ### end Alembic commands ###
