"""empty message

Revision ID: d12a30ab100e
Revises: 8156283d77c4
Create Date: 2017-08-01 16:35:39.206354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd12a30ab100e'
down_revision = '8156283d77c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('phone', sa.String(length=15), nullable=True))
    op.create_unique_constraint(None, 'queries', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'queries', type_='unique')
    op.drop_column('queries', 'phone')
    # ### end Alembic commands ###
