"""empty message

Revision ID: e455451361ab
Revises: 1c68bec3cf01
Create Date: 2017-07-18 22:50:09.266263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e455451361ab'
down_revision = '1c68bec3cf01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subissues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('issues', sa.Column('subissue_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'issues', 'subissues', ['subissue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_column('issues', 'subissue_id')
    op.drop_table('subissues')
    # ### end Alembic commands ###
