"""empty message

Revision ID: f38ddbbbd934
Revises: d12a30ab100e
Create Date: 2017-08-02 03:55:36.143989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f38ddbbbd934'
down_revision = 'd12a30ab100e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('phone', table_name='queries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('phone', 'queries', ['phone'], unique=True)
    # ### end Alembic commands ###
